### ISSUE TITLE
请教MWS广告接口的相关问题

### ISSUE THREAD

**Issue by laySpring** [jiangbingyang/amazon-advertising-api-csharp#1]
我在网上无意间看到您写的关于MWS的PPC广告报告数据获取、PPC广告管理的相关博客，非常感谢您的分享，里面都提到了【文档上没有列出来的类型】这个说法，请问一下这些文档外的类型是如何找到的呢？
现在市面上出现PPC广告管理，包含了设置定时开启和关闭广告、定时调价、自动调价、关键词优化等方面的接口，是否您提供的广告API也可以达到这种效果呢？
因为现在做的也是Amazon相关的接口和爬虫开发，正好也是C#，所以遇到很多问题都在一点点的摸索，而官方提供的文档确实有些东西没办法拿到，希望可以和您学习。

**Comment by 1992w** [comment]
你可以看看这个API https://advertising.amazon.com/  这个API需要用真实的美国公司资料申请，你刚才说的功能这个API都能满足

**Comment by laySpring** [comment]
收到，非常感谢您!!!另外我有一个很小白的问题请教，像这个API https://advertising.amazon.com/ ，到底应该归于AWS还是MWS呢？是否其他的API也存在这种情况，需要用美国公司资料申请之后才可以看到呢？再次感谢！

**Comment by 1992w** [comment]
advertising API 应该是独立的一个广告报表，目前我只了解到advertising  api需要用美国公司资料申请

**Comment by laySpring** [comment]
我看了一下，似乎是需要申请之后，登陆完成才可以正式使用这个API，这一步就是需要美国公司资料申请了吧。有点被资源（缺少美国公司资料）限制住了。

**Comment by 1992w** [comment]
https://images-na.ssl-images-amazon.com/images/G/01/AdProductsWebsite/downloads/Amazon_Advertising_API_Getting_Started_Guide._TTH_.pdf 这里有指南你可以看看。
没有美国公司资料的话，可能就用不了，advertising api 在登录授权的时候 scope的值是cpc_advertising:campaign_management   如果你没有提交过资料会提示你没有授权，参数无效

**Comment by laySpring** [comment]
非常感谢！！！我研究一下这个文档。谢谢大神指点。
