### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by 15768495614** [jiangbingyang/amazon-advertising-api-csharp#2]
使用这个api必须登录亚马逊吗？可不可以绕过亚马逊登录，防止店铺ip关联

**Comment by 1992w** [comment]
你可以在授权的那一步在关联店铺的那台电脑上操作，保存获得的token，然后程序定时刷新。之后的操作就不用必须在关联的那台电脑上操作了

**Comment by 15768495614** [comment]
你好，有一个参数code不是很明白为什么是一个字符串，这个方法是返回code？
![kqb t_ra3 3 i0 cw 2g](https://user-images.githubusercontent.com/39647869/45005018-ac8bff00-b023-11e8-9ea8-d84d206d02ab.png)

**Comment by 1992w** [comment]
那个code是在亚马逊登录后，亚马逊会把url重定向到我们设置好的一个url，同时会带上那个参数。 具体的流程你可以看看这个开发指南https://images-na.ssl-images-amazon.com/images/G/01/lwa/dev/docs/website-developer-guide._TTH_.pdf

**Comment by 15768495614** [comment]
我沙箱测试的时候可以用买家账号吗？为什么网站登录之后没有拿到刷新令牌？请求的时候报未授权的异常？

**Comment by 1992w** [comment]
使用advertising api的话， scope的值要加上cpc_advertising:campaign_management。    不过这个api之前需要拿真实的美国公司资料去申请，现在不知道还要不要。你可以去https://advertising.amazon.com/API 这里看看最新的。   前面两个问题，再看看最新的文档应该能找到答案， 我有一段时间没弄这个了，细节有点忘记了

**Comment by 15768495614** [comment]
你好，在调用amazon.Login.authorize的时候把scope设为profile是可以的，如果设为cpc_advertising:campaign_management，获取code的时候就会报错oauth errorinvalid_scope。为什么呢

**Comment by 15768495614** [comment]
访问令牌和刷新令牌都能拿到，为什么请求api时报Authentication failed呢

**Comment by 1992w** [comment]
scope的值是cpc_advertising:campaign_management，更多细节你可以参考文档https://advertising.amazon.com/API/docs/guides/authorization。

用cpc_advertising:campaign_management拿到令牌后，还是会提示未授权就是我之前说的，需要给亚马逊发邮件，把真实的美国公司资料发给他们，可能需要等几天才会收到回复，审核通过后，就不会提示未授权了。

**Comment by 15768495614** [comment]
是朋友给我申请的api,我看到了开发文档中Add your Website to your Security Profile,我需要添加安全配置吗？如果需要添加那就太麻烦了

**Comment by 1992w** [comment]
申请API比较简单，注册一个亚马逊的开发者账号就可以了。我觉得你可以先跟朋友确认一下，账号有没有发过资料给亚马逊，没有授权的话，api是用不了的，这个是最重要的步骤。
